### ISSUE TITLE
write Characteristics

### ISSUE THREAD

**Issue by torretorich** [Ficat/EasyBle#15]
I call write Characteristics with static value after the device is connected like that : 

```
if (characteristicInfo.writable) {
                    writeCharacteristic = characteristicInfo;
                    String str = "c100";
                    if (TextUtils.isEmpty(str)) {
                        Toast.makeText(getActivity(), getResources().getString(R.string.tips_write_operation), Toast.LENGTH_SHORT).show();
                        return;
                    }
                    BleManager.getInstance().write(device, e.getKey().uuid, writeCharacteristic.uuid, ByteUtils.hexStr2Bytes(str), writeCallback);
                }
```

```
private BleWriteCallback writeCallback = new BleWriteCallback() {
        @Override
        public void onWriteSuccess(byte[] data, BleDevice device) {
            Logger.e("write success:" + ByteUtils.bytes2HexStr(data));
        }

        @Override
        public void onFailure(int failCode, String info, BleDevice device) {
            Logger.e("write fail:" + info);
            Logger.e("write failCode:" + failCode);
        }
    };
```

and I get onFailure : 
write fail:write fail because of unknown reason
write failCode:201

@Ficat can you please help me to solve this ?

**Comment by Ficat** [comment]
Hello @torretorich , you can try to solve it from the following points .
1.Check if byte array value you writed is null.
2.When you call #write(), mark sure device isn't busy at this moment, because BLE commands must be sequential
3.For some device if we call write/read()  as soon as found BLE services_(Easyble calls back #onConnected() when discoverying service end)_, it may fail, so it's better to have a certain time interval between #onConnected() and write()
4.If the above doesn't work, maybe device err. I recommand you test this device by EasyBle sample APP

**Comment by torretorich** [comment]
I tested the device with EasyBle sample APP, it works fine.
Can you guide me how can i set the time interval in my above function.

**Comment by torretorich** [comment]
Thanks it's working now I got 'write success:' .
I modified the function with a time interval of 1 second.
